runtime: nodejs10

automatic_scaling:
  max_instances: 2
  
# instance_class: F4
# automatic_scaling:
#   target_cpu_utilization: 0.6
#   min_pending_latency: 30ms
#   max_pending_latency: automatic
#   max_concurrent_requests: 50
#   min_instances: 2

service: default
handlers:
  - url: /(.*\.(gif|png|jpg|svg|mp3|mp4))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|svg|mp3|mp4)$
  # All URLs beginning with /fonts are treated as paths to
  # static files in the fonts/ directory.
  - url: /fonts
    static_dir: public/fonts
  # All URLs beginning with /public are treated as paths to
  # static files in the public/ directory.
  - url: /public
    static_dir: public
  - url: /.*
    script: auto
    secure: always

env_variables:
  DEFAULT_LANG: 'en-us'